# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: /
    weight: 15 
  - name: Publications
    url: publications/
    weight: 30
  - name: Teaching
    url: teaching/
    weight: 45 
